######################################################################################
# Title:         Saltbox: Resources | Tasks | Docker | Set Docker Devices Variable   #
# Author(s):     desimaniac, salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                                 #
# --                                                                                 #
######################################################################################
#                   GNU General Public License v3.0                                  #
######################################################################################
---
- name: Resources | Tasks | Docker | Set Docker Devices Variable | Check if '/dev/dri' exists
  ansible.builtin.stat:
    path: "/dev/dri"
  register: dev_dri

- name: Resources | Tasks | Docker | Set Docker Devices Variable | Rebuild 'docker_devices' variable
  when: dev_dri.stat.exists
  block:
    - name: Resources | Tasks | Docker | Set Docker Devices Variable | Set 'docker_devices_var_name' temp variable
      ansible.builtin.set_fact:
        docker_devices_var_name: "{{ role_name + '_docker_devices_default' }}"

    - name: Resources | Tasks | Docker | Set Docker Devices Variable | Set 'docker_devices' variable # noqa var-naming[no-jinja]
      ansible.builtin.set_fact:
        "{{ docker_devices_var_name }}": "{{ ['/dev/dri:/dev/dri'] + lookup('docker_var', '_docker_devices_default', default=[]) }}"
