##################################################################################
# Title:         Saltbox: Resources | Tasks | Directories | Create Directories   #
# Author(s):     salty                                                           #
# URL:           https://github.com/saltyorg/Saltbox                             #
# --                                                                             #
##################################################################################
#                   GNU General Public License v3.0                              #
##################################################################################
---
- name: Resources | Tasks | Directories | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ lookup('role_var', '_paths_owner', default=user.name) }}"
    group: "{{ lookup('role_var', '_paths_group', default=user.name) }}"
    mode: "{{ lookup('role_var', '_paths_permissions', default='0775') }}"
    recurse: "{{ lookup('role_var', '_paths_recursive', default=false) }}"
  with_items: "{{ lookup('role_var', '_paths_folders_list')
                  + lookup('role_var', '_paths_folders_list_custom', default=[]) }}"
