##########################################################################
# Title:         Saltbox: Portainer | Default Variables                  #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

portainer_name: portainer

################################
# Settings
################################

portainer_role_business_edition: false

################################
# Paths
################################

portainer_role_paths_folder: "{{ portainer_name }}"
portainer_role_paths_location: "{{ server_appdata_path }}/{{ portainer_role_paths_folder }}"
portainer_role_paths_folders_list:
  - "{{ portainer_role_paths_location }}"

################################
# Web
################################

portainer_role_web_subdomain: "{{ portainer_name }}"
portainer_role_web_domain: "{{ user.domain }}"
portainer_role_web_port: "9000"
portainer_role_web_url: "{{ 'https://' + (lookup('role_var', 'web_subdomain') + '.' + lookup('role_var', '_web_domain')
                         if (lookup('role_var', '_web_subdomain') | length > 0)
                         else lookup('role_var', '_web_domain')) }}"

################################
# DNS
################################

portainer_role_dns_record: "{{ lookup('role_var', '_web_subdomain') }}"
portainer_role_dns_zone: "{{ lookup('role_var', '_web_domain') }}"
portainer_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

portainer_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
portainer_role_traefik_middleware_default: "{{ traefik_default_middleware
                                               + (',themepark-' + portainer_name
                                                 if (lookup('role_var', '_themepark_enabled') and global_themepark_plugin_enabled)
                                                 else '') }}"
portainer_role_traefik_middleware_custom: ""
portainer_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
portainer_role_traefik_enabled: true
portainer_role_traefik_api_enabled: true
portainer_role_traefik_api_endpoint: "PathPrefix(`/api/websocket/`)"

################################
# THEME
################################

# Options can be found at https://github.com/themepark-dev/theme.park
portainer_role_themepark_enabled: false
portainer_role_themepark_theme: "{{ global_themepark_theme }}"

################################
# Docker
################################

# Container
portainer_role_docker_container: "{{ portainer_name }}"

# Image
portainer_role_docker_image_pull: true
portainer_role_docker_image_tag: "latest"
portainer_role_docker_image: "{{ ('portainer/portainer-ee:'
                              if lookup('role_var', '_business_edition')
                              else 'portainer/portainer-ce:') + portainer_role_docker_image_tag }}"

# Ports
portainer_role_docker_ports_defaults: []
portainer_role_docker_ports_custom: []
portainer_role_docker_ports: "{{ lookup('role_var', '_docker_ports_defaults')
                                 + lookup('role_var', '_docker_ports_custom') }}"

# Envs
portainer_role_docker_envs_default:
  TZ: "{{ tz }}"
portainer_role_docker_envs_custom: {}
portainer_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default')
                                | combine(lookup('role_var', '_docker_envs_custom')) }}"

# Commands
portainer_role_docker_commands_default: []
portainer_role_docker_commands_custom: []
portainer_role_docker_commands: "{{ lookup('role_var', '_docker_commands_default')
                                    + lookup('role_var', '_docker_commands_custom') }}"

# Volumes
portainer_role_docker_volumes_default:
  - "{{ portainer_role_paths_location }}:/data"
  - "/var/run/docker.sock:/var/run/docker.sock"
portainer_role_docker_volumes_custom: []
portainer_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default')
                                   + lookup('role_var', '_docker_volumes_custom') }}"

# Devices
portainer_role_docker_devices_default: []
portainer_role_docker_devices_custom: []
portainer_role_docker_devices: "{{ lookup('role_var', '_docker_devices_default')
                                   + lookup('role_var', '_docker_devices_custom') }}"

# Hosts
portainer_role_docker_hosts_default: {}
portainer_role_docker_hosts_custom: {}
portainer_role_docker_hosts: "{{ docker_hosts_common
                                 | combine(lookup('role_var', '_docker_hosts_default'))
                                 | combine(lookup('role_var', '_docker_hosts_custom')) }}"

# Labels
portainer_role_docker_labels_default: {}
portainer_role_docker_labels_custom: {}
portainer_role_docker_labels_themepark:
  - '{ "traefik.http.middlewares.themepark-{{ portainer_name }}.plugin.themepark.app": "portainer" }'
  - '{ "traefik.http.middlewares.themepark-{{ portainer_name }}.plugin.themepark.theme": "{{ lookup("role_var", "_themepark_theme") }}" }'
portainer_role_docker_labels: "{{ docker_labels_common
                                  | combine(lookup('role_var', '_docker_labels_default'))
                                  | combine((lookup('role_var', '_docker_labels_themepark')
                                            if (lookup('role_var', '_themepark_enabled') and global_themepark_plugin_enabled)
                                            else {}),
                                            lookup('role_var', '_docker_labels_custom')) }}"

# Hostname
portainer_role_docker_hostname: "{{ portainer_name }}"

# Networks
portainer_role_docker_networks_alias: "{{ portainer_name }}"
portainer_role_docker_networks_default: []
portainer_role_docker_networks_custom: []
portainer_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default')
                                    + lookup('role_var', '_docker_networks_custom') }}"

# Capabilities
portainer_role_docker_capabilities_default: []
portainer_role_docker_capabilities_custom: []
portainer_role_docker_capabilities: "{{ lookup('role_var', '_docker_capabilities_default')
                                        + lookup('role_var', '_docker_capabilities_custom') }}"

# Security Opts
portainer_role_docker_security_opts_default: []
portainer_role_docker_security_opts_custom: []
portainer_role_docker_security_opts: "{{ lookup('role_var', '_docker_security_opts_default')
                                         + lookup('role_var', '_docker_security_opts_custom') }}"

# Restart Policy
portainer_role_docker_restart_policy: unless-stopped

# State
portainer_role_docker_state: started
