#########################################################################
# Title:         Saltbox: Hetzner Role                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Hetzner Tasks"
  ansible.builtin.include_tasks: "subtasks/hetzner.yml"

- name: "Restart Tasks"
  ansible.builtin.include_tasks: "subtasks/restart.yml"
  when: reboot_is_necessary and (not continuous_integration)
