#########################################################################
# Title:         Saltbox: Pre-Tasks                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT Tasks
  ansible.builtin.include_tasks: "subtasks/apt.yml"

- name: Git Tasks
  ansible.builtin.include_tasks: "subtasks/git.yml"

- name: Variables Tasks
  ansible.builtin.include_tasks: "subtasks/variables.yml"
  when: (playbook_dir != "/srv/git/saltbox" and not continuous_integration) or (playbook_dir != "/home/runner/work/Saltbox/Saltbox" and continuous_integration)
