##########################################################################
# Title:         Saltbox: Authelia | Authentication Backend Task         #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Auth | Import File Backend Task
  ansible.builtin.include_tasks: "subtasks/file_backend.yml"
  when: (lookup('role_var', '_authentication_backend', role='authelia') == 'file')

- name: Auth | Import LDAP Backend Task
  ansible.builtin.include_tasks: "subtasks/ldap_backend.yml"
  when: (lookup('role_var', '_authentication_backend', role='authelia') == 'ldap')
