##########################################################################
# Title:         Saltbox: Authelia | LDAP Backend Task                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: LDAP | Get FLD
  ansible.builtin.shell: |
    {{ saltbox_python }} -c "from tld import get_tld; res = get_tld(\"http://{{ lookup('role_var', '_web_domain') | default(user.domain) }}\", as_object=True); print(res.tld)"
  register: authelia_tld

- name: LDAP | Get FLD
  ansible.builtin.shell: |
    {{ saltbox_python }} -c "from tld import get_tld; res = get_tld(\"http://{{ lookup('role_var', '_web_domain') | default(user.domain) }}\", as_object=True); print(res.domain)"
  register: authelia_domain

- name: LDAP | Import default 'configuration.yml'
  ansible.builtin.template:
    src: configuration.yml.j2
    dest: "{{ authelia_role_paths_location }}/configuration.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
  when: (not authelia_config_stat.stat.exists)

- name: LDAP | Format 'configuration.yml'
  ansible.builtin.shell: "yyq -i {{ authelia_role_paths_location }}/configuration.yml"
  when: (not authelia_config_stat.stat.exists)

- name: LDAP | Import lldap Role
  ansible.builtin.include_role:
    name: lldap
