##########################################################################
# Title:         Saltbox: Authelia | Settings Task                       #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Settings | Load encryption_key value
  ansible.builtin.shell: |
    yyq '.storage.encryption_key' {{ authelia_role_paths_location }}/configuration.yml
  register: authelia_encryption_key

- name: Settings | Add encryption_key to config file
  ansible.builtin.shell: |
    yyq -i '.storage.encryption_key = "{{ lookup('password', '/dev/null', chars=['ascii_letters', 'digits'], length=64) }}"' {{ authelia_role_paths_location }}/configuration.yml
  become: true
  become_user: "{{ user.name }}"
  when: authelia_encryption_key.stdout == "null"

- name: Settings | Load session.redis.host value
  ansible.builtin.shell: |
    yyq '.session.redis.host' {{ authelia_role_paths_location }}/configuration.yml
  register: authelia_session_redis_host

- name: Settings | Change session.redis.host value to 'authelia_redis'
  ansible.builtin.shell: |
    yyq -i '.session.redis.host = "authelia-redis"' {{ authelia_role_paths_location }}/configuration.yml
  become: true
  become_user: "{{ user.name }}"
  when: (authelia_session_redis_host.stdout == "redis") or (authelia_session_redis_host.stdout == "authelia_redis")
