##########################################################################
# Title:         Saltbox: Light LDAP | Default Variables                 #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

lldap_name: "lldap"

################################
# Settings
################################

# Toggles if the configuration template uses SMTP or not.
lldap_role_smtp_enabled: false
# The SMTP server.
lldap_role_smtp_server: "smtp.gmail.com"
# The SMTP port.
lldap_role_smtp_port: "587"
# How the connection is encrypted, either "NONE" (no encryption), "TLS" or "STARTTLS".
lldap_role_smtp_encryption: "TLS"
# The SMTP user, usually your email address.
lldap_role_smtp_user: "sender@gmail.com"
# The SMTP password.
lldap_role_smtp_password: "password"
# is a free-form name, followed by an email between <>.
lldap_role_smtp_from: "LLDAP Admin <sender@gmail.com>"
# The header field, optional: how the sender appears in the email.
# The first is a free-form name, followed by an email between <>.
lldap_role_smtp_reply_to: "Do not reply <noreply@localhost>"

################################
# Paths
################################

lldap_role_paths_folder: "{{ lldap_name }}"
lldap_role_paths_location: "{{ server_appdata_path }}/{{ lldap_role_paths_folder }}"
lldap_role_paths_folders_list:
  - "{{ lldap_role_paths_location }}"

################################
# Web
################################

lldap_role_web_subdomain: "lldap"
lldap_role_web_domain: "{{ user.domain }}"
lldap_role_web_port: "17170"
lldap_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain') + '.' + lookup('role_var', '_web_domain')
                     if (lookup('role_var', '_web_subdomain') | length > 0)
                     else lookup('role_var', '_web_domain')) }}"

################################
# DNS
################################

lldap_role_dns_record: "{{ lookup('role_var', '_web_subdomain') }}"
lldap_role_dns_zone: "{{ lookup('role_var', '_web_domain') }}"
lldap_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

lldap_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
lldap_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
lldap_role_traefik_middleware_custom: ""
lldap_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
lldap_role_traefik_enabled: true
lldap_role_traefik_api_enabled: false
lldap_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
lldap_role_docker_container: "{{ lldap_name }}"

# Image
lldap_role_docker_image_pull: true
lldap_role_docker_image_repo: "nitnelave/lldap"
lldap_role_docker_image_tag: "stable"
lldap_role_docker_image: "{{ lookup('role_var', '_docker_image_repo')
                             + ':' + lookup('role_var', '_docker_image_tag') }}"

# Ports
lldap_role_docker_ports_defaults: []
lldap_role_docker_ports_custom: []
lldap_role_docker_ports: "{{ lookup('role_var', '_docker_ports_defaults')
                             + lookup('role_var', '_docker_ports_custom') }}"

# Envs
lldap_role_docker_envs_default:
  TZ: "{{ tz }}"
  UID: "{{ uid }}"
  GID: "{{ gid }}"
lldap_role_docker_envs_custom: {}
lldap_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default')
                            | combine(lookup('role_var', '_docker_envs_custom')) }}"

# Commands
lldap_role_docker_commands_default: []
lldap_role_docker_commands_custom: []
lldap_role_docker_commands: "{{ lookup('role_var', '_docker_commands_default')
                                + lookup('role_var', '_docker_commands_custom') }}"

# Volumes
lldap_role_docker_volumes_default:
  - "{{ lldap_role_paths_location }}:/data"
lldap_role_docker_volumes_custom: []
lldap_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default')
                               + lookup('role_var', '_docker_volumes_custom') }}"

# Devices
lldap_role_docker_devices_default: []
lldap_role_docker_devices_custom: []
lldap_role_docker_devices: "{{ lookup('role_var', '_docker_devices_default')
                               + lookup('role_var', '_docker_devices_custom') }}"

# Hosts
lldap_role_docker_hosts_default: {}
lldap_role_docker_hosts_custom: {}
lldap_role_docker_hosts: "{{ docker_hosts_common
                             | combine(lookup('role_var', '_docker_hosts_default'))
                             | combine(lookup('role_var', '_docker_hosts_custom')) }}"

# Labels
lldap_role_docker_labels_default: {}
lldap_role_docker_labels_custom: {}
lldap_role_docker_labels: "{{ docker_labels_common
                              | combine(lookup('role_var', '_docker_labels_default'))
                              | combine(lookup('role_var', '_docker_labels_custom')) }}"

# Hostname
lldap_role_docker_hostname: "{{ lldap_name }}"

# Networks
lldap_role_docker_networks_alias: "{{ lldap_name }}"
lldap_role_docker_networks_default: []
lldap_role_docker_networks_custom: []
lldap_role_docker_networks: "{{ docker_networks_common
                                + lookup('role_var', '_docker_networks_default')
                                + lookup('role_var', '_docker_networks_custom') }}"

# Capabilities
lldap_role_docker_capabilities_default: []
lldap_role_docker_capabilities_custom: []
lldap_role_docker_capabilities: "{{ lookup('role_var', '_docker_capabilities_default')
                                    + lookup('role_var', '_docker_capabilities_custom') }}"

# Security Opts
lldap_role_docker_security_opts_default: []
lldap_role_docker_security_opts_custom: []
lldap_role_docker_security_opts: "{{ lookup('role_var', '_docker_security_opts_default')
                                     + lookup('role_var', '_docker_security_opts_custom') }}"

# Restart Policy
lldap_role_docker_restart_policy: unless-stopped

# State
lldap_role_docker_state: started
