##########################################################################
# Title:         Saltbox: Autoheal | Default Variables                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

autoheal_name: autoheal

################################
# Docker
################################

# Container
autoheal_role_docker_container: "{{ autoheal_name }}"

# Image
autoheal_role_docker_image_pull: true
autoheal_role_docker_image_tag: "latest"
autoheal_role_docker_image: "willfarrell/autoheal:{{ autoheal_role_docker_image_tag }}"

# Envs
autoheal_role_docker_envs_default:
  AUTOHEAL_CONTAINER_LABEL: "autoheal"
autoheal_role_docker_envs_custom: {}
autoheal_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='autoheal')
                               | combine(lookup('role_var', '_docker_envs_custom', role='autoheal')) }}"

# Volumes
autoheal_role_docker_volumes_default:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "/etc/localtime:/etc/localtime:ro"
autoheal_role_docker_volumes_custom: []
autoheal_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='autoheal')
                                  + lookup('role_var', '_docker_volumes_custom', role='autoheal') }}"

# Hostname
autoheal_role_docker_hostname: "{{ autoheal_name }}"

# Networks
autoheal_role_docker_networks_alias: "{{ autoheal_name }}"
autoheal_role_docker_networks_default: []
autoheal_role_docker_networks_custom: []
autoheal_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='autoheal')
                                   + lookup('role_var', '_docker_networks_custom', role='autoheal') }}"

# Restart Policy
autoheal_role_docker_restart_policy: unless-stopped

# State
autoheal_role_docker_state: started
